### ISSUE TITLE
How to deal with data dir

### ISSUE THREAD

**Issue by oscgonfer** [fablabbcn/smartcitizen-data-framework#5]
The framework makes use of a `data` directory to hold calibration, blueprints and local data sources as raw and processed data, models and so on.

With the changes by @mcsage, for `setup.py`, the data folder could not be used properly since:
1. it could grow if data and models are accumulated in it and go unadvertised for someone that doesn't know where to look for
2. it could be rendered inaccessible if moved to the site-packages as a package_data folder

So, should we include a step to make a ~/.scdata/data folder in which or another configurable directory in an .env file? @mcsage any proposal?

**Comment by mcsage** [comment]
Hi @oscgonfer,

I like the idea to store the data in ~/.scdata/data. What do you think about setting the default to ~/.scdata/data if not otherwise configured in .env.

**Comment by oscgonfer** [comment]
I guess we could take the same approach as [mpsyt](https://github.com/mps-youtube/mps-youtube/blob/develop/mps_youtube) as done to manage the [downloads directory](https://github.com/mps-youtube/mps-youtube/blob/develop/mps_youtube/paths.py):

https://github.com/mps-youtube/mps-youtube/blob/develop/mps_youtube/paths.py#L17-L18

We should then add this as the first thing to do when using scdata and it's `_config` object (meant to be accessible to all classes).

**Comment by oscgonfer** [comment]
Have been working on this for a while and included it during the package config stage.
There are some checks pending for windows, but should be fine for the rest. Now it will create:
- `.config/scdata` with a config.yaml for paths and data dealing configs (to be documented)
- `.cache/scdata` with all the data structure as before
This should follow https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html.
